### ISSUE TITLE
Why R 4.4 minimum?

### ISSUE THREAD

**Issue by mfansler** [kullrich/CRBHits#2]
Setting an R 4.4 minimum is rather extreme. Are there particular features in R 4.4 that the code for this package relies upon?

https://github.com/kullrich/CRBHits/commit/75a9ea7f6f7e4450574f2dcf76c0a662841c39d9#diff-9cc358405149db607ff830a16f0b4b21f7366e3c99ec00d52800acebe21b231cL17

**Comment by kullrich** [comment]
Hi @mfansler,

I switched the Ka/Ks calculation to use my `MSA2dist` package, which itself is a Bioconductor package (https://www.bioconductor.org/packages/release/bioc/html/MSA2dist.html).

The advantage is, that the kaks_calculator2 dependency has gone and is completely ported to R with Rcpp. It offers some other features like `pal2nal` creation.

Hope, that explains a bit the setting of the newer R version as the minimum.

**Comment by mfansler** [comment]
Thanks for the quick reply! So it's not really that it is incompatible with earlier R versions, but instead that it has a minimum requirement for `MSAdist` and Bioconductor has locked that into R 4.4.

Sounds good!
